# 8.异常的陷阱
- 正确关闭资源的方式
	- finally块关闭物理资源，以保证关闭操作总是会执行
		- 注意只要JVM不退出，即 return/continue/break都不能阻止finally的执行，
		- 这些都只能导致方法结束，但是方法结束前系统会先检查是否有finally块，有则执行，然后才是退出方法的流程(return 等)
		- 但是在try块中有System.exit(0);语句将导致finally不被执行
		- 这种情况下，可以通过为系统注册一个关闭钩子的方式来清理资源
		- 程序试图抛出异常前，也会先执行finally块中的代码
			- 不要在finally中调用可能引起异常的方法，因为这可能导致该方法的异常不能被正常抛出，甚至StackOverFlowError错误也不能终止程序，只能强行结束java.exe进程的方式来退出。
	- 关闭每个资源之前保证引用该资源的变量不为空
	- 为每个物理资源使用单独的try...catch块来关闭，保证关闭资源时引发的异常不会影响到其他资源的关闭
- java7以后关闭的简便方式
	- 在try(){} 后的()里声明、初始化资源，系统将自动关闭
	- 资源类都实现了Closeable接口或者AutoCloseable接口
- 不要用catch代替流程控制
- 异常类型
	- runtime:任意地方都能catch
	- checked:try块中有可能抛出这类异常时才能catch
		- catch块中明确知道如何处理
		- 不知如何处理，定义所在方法时抛出
- 继承父类时只能抛出父类抛出的异常或者其子异常，实现多个接口的，可以抛出多个接口抛出的异常及其子异常的交集，或者不抛出。
- java7中增强的throw语句
	- 判断所含方法可能抛出异常的种类声明具体的异常类型，而不是方法里catch什么就抛什么
